### ISSUE TITLE
Vpp make gpu memory leak in val-surface-sharing

### ISSUE THREAD

**Issue by DyncEric** [intel/libvpl-tools#2]
Hi :
I used cmd like this: 

val-surface-sharing -i ../out-4k.nv12 -surface_component vpp_in -sc nv12 -sw 3840 -sh 2160 -dc nv12 -dw 640 -dh 360 -surface_type d3d11 -mode shared -o vpp.nv12

Found out the gpu memory is increased quickly, how to resolved this problem?

**Comment by akwrobel** [comment]
We will look into this, can you expand on your use case for this test tool?

**Comment by jonrecker** [comment]
Thank you for filing the issue. For VPP and encode it looks like the ID3D11Texture2D returned by CreateSurfaceToShare() is not being released before it goes out of scope. This will be updated in the next libvpl-tools release.

**Comment by mav-intel** [comment]
Fixed as of 756eaeb48527b345729497bc0ac8e6a309f2dfab

**Comment by DyncEric** [comment]
Thanks for your work.
